steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'HandleRequest', '--trigger-http', '--runtime', 'go113', '--entry-point', 'HandleRequest']
    dir: 'functions/autodeploy'