steps:
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'version']
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'intcatalogapi']
    dir: 'functions/autodeploy'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'intcatalogapi', '--trigger-http', '--runtime', 'go113', '--entry-point', 'HandleRequest']
    dir: 'functions/autodeploy'